name: Regression Tests

on:
  push:
    branches: [ main ]

jobs:
  web_tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Node 14
      run: |
        curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
        sudo apt-get install -y nodejs
    - name: Preparation
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb ca-certificates net-tools netcat gnupg ffmpeg libgtk-3-0 libgdk-pixbuf2.0-dev libxcomposite-dev libdbus-glib-1-2 libatk-bridge2.0-0 wget libgbm1 libnss3 libxss1 libasound2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install robotframework-browser
    - name: Run Browser Init
      run: rfbrowser init
    - name: Run WEB Tests
      run: |
        chmod +x ./run.bat
        ./run.bat
    - name: Upload WEB Tests Results
      uses: actions/upload-artifact@v2.3.1
      if: always()
      with:
        name: web-reports
        path: logs
    - name: Download reports
      uses: actions/download-artifact@v1
      with:
        name: reports
    - name: Send report to commit
      uses: joonvena/robotframework-reporter-action@v2
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
